### ISSUE TITLE
Extension was taken down from Chrome Web Store and I know how to reinstate it

### ISSUE THREAD

**Issue by bershanskiy** [sveltejs/svelte-devtools#126]
**Describe the bug**
The official extension listing on Chrome Web Store is not available.

**To Reproduce**
1. Go to project README.md
2. Click on ["Chrome addon page"](https://chrome.google.com/webstore/detail/svelte-devtools/ckolcbmkjpjmangdbmnkpjigpkddpogn) in the document
3. Observe "404. That’s an error."

**Expected behavior**
Extension page is visible and extension can be installed.

**Environment**
 - Any

**Additional context**
I can prepare a series of PRs which will be small and trivial to review, but will address all remaining issues with MV3 compatibility allowing extension to be published again. I tried to merge a few of these changes back in 2021, but by then extension development was winding down and 

Specifically:
 1. Get rid of `chrome.tabs.executeScript({code: ....})` since `code` is a known XSS sink and causes issues during review [(used here)](https://github.com/sveltejs/svelte-devtools/blob/master/src/background.js#L58). This is the likely reason for the take-down, but store listing owner would need to look into the store console to make sure.
 2. Get rid of installation warning about "changing all the content" on every page (remove `tabs` and `<all_urls>` permissions, that is make extension entirely "permission-less").
 3. (optional) Get rid of global background state which requires background persistence for the entire duration of debugging session.

After extension reinstatement/publication under a different extension id, I can also add support for debugging sub-frames (something not really supported now).

**Comment by Maltaesh** [comment]
@Rich-Harris can You help with some info, about this?
