### ISSUE TITLE
Add component inspection button

### ISSUE THREAD

**Issue by ljirari-decathlon** [sveltejs/svelte-devtools#166]
**Describe the bug**
Hi, i've built the last version availabe on master branch but i don't have the component selector.
<img width="629" alt="image" src="https://github.com/sveltejs/svelte-devtools/assets/134631850/42a2935f-1860-4617-ac25-82030df34d90">

**Comment by ignatiusmb** [comment]
The inspector 'button' is disabled for components as there's no equivalent DOM node it can inspect on the 'elements' tab, but it's still referenced in the console with `$n` when you select the component, is that what you're looking for?

**Comment by ljirari-decathlon** [comment]
i mean this one :
<img width="36" alt="image" src="https://github.com/sveltejs/svelte-devtools/assets/134631850/f9f6a07e-61e4-426d-af67-5c876f85e156">

**Comment by WarningImHack3r** [comment]
@ljirari-decathlon I agree it would be useful but it's not a bug, it's just not part of the DevTools. Just look at the image in the README, nothing is missing.

**Comment by ignatiusmb** [comment]
This will come as a new feature in the upcoming updates, it wasn't included in the initial v2 release to make sure we can get it published as soon as possible.

**Comment by GimpMaster** [comment]
@ignatiusmb  - Looking forward to this feature. One thing I find annoying with sveltekit applications if I have to go an expand so many items just to get down into a single component. If there was a picker that I could click on and then choose a component or element in the rendered view that would auto-expand everything, that would be amazing.

Essentially thats how I work with normal inspector dev tools. I don't want to expand all the collapsed items, I just click in the general area of what I want to look at with the selector and BAM, its open to approximate area.

**Comment by GimpMaster** [comment]
Sounds great! Thank you

**Comment by ignatiusmb** [comment]
> [...] the Collapse icon was not expanding the tree.

If it's the one on the left side of the element, I can see how it's not that intuitive since the native devtools can click on it to toggle the expand/collapse state, but we use double-clicks to do those. Otherwise, I don't think we have another collapse icon.

We may be getting off-topic here, could you please open an issue if that's what you meant, thanks.

**Comment by GimpMaster** [comment]
Ah, yeah I was only ever trying single click not double click since that is how regular dev tools area.
