### ISSUE TITLE
many console.logs

### ISSUE THREAD

**Issue by cannap** [sveltejs/svelte-devtools#170]
Open Devtools 
this happens when something changes (state)
![image](https://github.com/sveltejs/svelte-devtools/assets/1394151/652750aa-b3fc-4167-b93e-ef87a39332f0)

thanks for you work!

**Comment by ignatiusmb** [comment]
Gah, that was a development leftover that must've slipped through when preparing the bundle locally for the first submission. I'll try to automate the publishing steps using GH actions, now that the store link is available. Thanks for the report!

**Comment by ignatiusmb** [comment]
The new build [`v2.0.1`](https://github.com/sveltejs/svelte-devtools/releases/tag/v2.0.1) has been published to the store
