### ISSUE TITLE
Cannot install in Arc browser

### ISSUE THREAD

**Issue by sillvva** [sveltejs/svelte-devtools#175]
**Describe the bug**
I am unable to install this in the Arc browser. 

**Troubleshooting steps already tried**
- I have already tried starting the browser and computer, but it still does not install. 
- I tried installing the Solid DevTools extension to see if it was me, but it installed without any issues. 
- I tried 2 other extensions as well with no issues. It seems to just be the Svelte DevTools extension.

**To Reproduce**

1. Open Arc
2. Go to the Chrome Webstore extension page
3. Click the `Add to Chrome` button
4. See the button revert to `Add to Chrome` without installing the extension.

![CleanShot 2023-11-11 at 09 09 00](https://github.com/sveltejs/svelte-devtools/assets/5138384/4b9bf593-9b7f-4eac-b9a6-129a9d4208fb)

**Expected behavior**
Extension should install. Arc is a chromium browser and supports the Chrome Webstore extensions.

**Environment**

-   Arc 1.15.2
-   Extension 2.0.1

**Comment by WarningImHack3r** [comment]
Try restarting Arc/rebooting your PC because I just got it working. It seems more like a Chromium/Chrome Web Store bug than an Arc issue anyway (inspecting the console should help).

**Comment by ignatiusmb** [comment]
Thanks for checking @WarningImHack3r

I'm afraid I won't be able to test this out (it's still on the waitlist for windows), but I also can't really help you if it's a bug from the web store or the arc browser as we have no control over both of those.

**Comment by WarningImHack3r** [comment]
@ignatiusmb you can safely close this issue in my opinion :)

**Comment by ignatiusmb** [comment]
Closing per @WarningImHack3r's confirmation :)
