### ISSUE TITLE
Cannot see devtools tab

### ISSUE THREAD

**Issue by buhodev** [sveltejs/svelte-devtools#176]
**Describe the bug**
After installing the extension from the store, reloading Chrome, restarting my PC, clicking on the Svelte Devtools extension icon, etc. The tab doesn't appear in my devtools.

![image](https://github.com/sveltejs/svelte-devtools/assets/105121122/5de6510e-b4f4-4a9b-909f-570853160898)

**To Reproduce**

1. Install extension from chrome store
2. Visit localhost with a sveltekit project running in dev mode
3. Click on extension icon (this does nothing)
4. Open devtools
5. See error: (Svelte Devtools tab doesn't appear)

**Expected behavior**
Svelte Devtools tab should appear

**Environment**

-   Browser with version [Chrome 119.0.6045.124 (Build oficial) (64 bits)]
-   Devtools version [2.0.1, from chrome store; 2.0.0, built from master]
-   Svelte version [4.2.3]

**Additional context**
Great talk! :smile:

**Comment by Gokulnath31** [comment]
Facing the same issue mentioned above

**Comment by ignatiusmb** [comment]
Heya, thank you! Regarding the panel not showing up in the tabs, can you make sure all the options in the "Service workers" page are turned off (as shown in the image below). 

![image](https://github.com/sveltejs/svelte-devtools/assets/8156777/528e53e0-d09b-48f9-895f-4d5a1c3618d9)

If it still doesn't show up, it may be some other options that was tweaked that I haven't encountered yet. In that case, you may need to reinstall your browser. You could also try installing the extension on a fresh install of another chromium browser to make sure it works on the default settings on your device.

**Comment by buhodev** [comment]
It worked. Thanks :smile:

**Comment by MrRoyce** [comment]
Same for me.  Not working 
Chrome: M1 MBP Version 121.0.6167.85 (Official Build) (arm64)
Svelte: 4.2.8
