### ISSUE TITLE
Can't get this to work :( 

### ISSUE THREAD

**Issue by vexkiddy** [sveltejs/svelte-devtools#184]
**Describe the bug**
I've installed the latest version from the chrome store. I get the icon in the extension toolbar but no 'svelte' tab in dev tools

**To Reproduce**
I'm using Sveltekit 2.0 with Svelte 4.0 + chrome. I'm developing an application and running it via localhost. It's not hosted anywhere.

**Comment by ignatiusmb** [comment]
Without any additional information, I can only assume that you're experiencing #176, can you try and check if https://github.com/sveltejs/svelte-devtools/issues/176#issuecomment-1807846208 solves that for you?
