### ISSUE TITLE
SvelteKit (Vite) hot reload requires reloading the extension (Firefox)

### ISSUE THREAD

**Issue by davidjayb** [sveltejs/svelte-devtools#189]
**Describe the bug**
Using SvelteKit with Vite, every time there is a code update served by Vite the Svelte Devtools needs to be reloaded. The plugin becomes unresponsive until reloaded.

**To Reproduce**

1. Open Svelte Devtools
2. Go to your webpage
3. Update a page/component

**Expected behavior**
When a component is updated the plugin should reflect the updated code without requiring closing the devtools and re-opening.

**Environment**

-   Firefox 124.0.1
-   built from master
-   Svelte 4.2.11

**Additional context**

This seems to be a Firefox specific bug, or related to changes in master that have not been released. Using Chrome with the extension from the marketplace I was unable to reproduce this bug.

**Comment by ignatiusmb** [comment]
Would it be possible for you to record the behavior? I couldn't seem to make it unresponsive with a fresh Svelte+Vite or SvelteKit project, the only issue I can see is with HMR which is reported in #125

**Comment by davidjayb** [comment]
Ah yes, it is related to HMR.

**Comment by ignatiusmb** [comment]
Thanks for the confirmation, closing in favor of #125
