### ISSUE TITLE
Support "Install from file" in Firefox

### ISSUE THREAD

**Issue by nemkicsiaron** [sveltejs/svelte-devtools#190]
**Describe the bug**
Trying to add the extension to Firefox via "Install from file" fails because "the app appears to be corrupt":
![image](https://github.com/sveltejs/svelte-devtools/assets/64364380/f0b9356a-56a7-4479-8159-fbdb48c77758)

**To Reproduce**
Try adding the newest release to Firefox

**Expected behavior**

**Environment**

-   Firefox Version 124.0.1 (64-bit)
-   Devtools version 2.2.0 .zip Release [e.g. 1.3.1, built from master]

**Additional context**
Running on Windows 11

**Comment by davidjayb** [comment]
You need to add this through `Load Temporary Add-on` in about:debugging:

https://extensionworkshop.com/documentation/develop/temporary-installation-in-firefox/

**Comment by ignatiusmb** [comment]
Yes, please load it as a temporary add-on for the time being. We're still in the process of validating the extension before it can be loaded from "Install from file". I'll adjust the title to reflect it clearer.

**Comment by ignatiusmb** [comment]
Per [v2.2.1 release](https://github.com/sveltejs/svelte-devtools/releases/tag/v2.2.1), `.xpi` files are now available to download and install for Firefox.

**Comment by rdrpenguin04** [comment]
Looks like README still needs to be updated to reflect the xpi files being available

**Comment by ignatiusmb** [comment]
@rdrpenguin04 thanks! #221
