### ISSUE TITLE
Can't download extension

### ISSUE THREAD

**Issue by MoinJulian** [sveltejs/svelte-devtools#215]
**Describe the bug**
If I try to download the extension I get the error that the Manifest is ivalid

**To Reproduce**

1. Go to 'https://chromewebstore.google.com/detail/svelte-devtools/kfidecgcdjjfpeckbblhmfkhmlgecoff?pli=1'
2. Click on 'Add'
3. See error ("Fehler beim Herunterladen: Invalid Manifest")

In English:

Error during Installation: Invalid Manifest 

**Expected behavior**
I would have expected that the extension gets downloaded but it doesn't

**Environment**

-   Browser with version [chrome 117.0.5938.132]

**Comment by ignatiusmb** [comment]
You'll need to update your Chrome as the minimum browser version was bumped up to v121 as of [v2.2.0](https://github.com/sveltejs/svelte-devtools/releases/tag/v2.2.0) release.

I was trying to think of ways to notify existing users if I were to add this [enforcement](https://developer.chrome.com/docs/extensions/reference/manifest/minimum-chrome-version#enforcement) and kind of forgot about it. Thinking about it again, I guess there's nothing we can do from the extension's side other than to hope the browser gets updated and in turn will also update the extension. Will add the `"minimum_chrome_version"` key in the next release.
