### ISSUE TITLE
pnpm build  ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL  Command "build" not found

### ISSUE THREAD

**Issue by leafOfTree** [sveltejs/svelte-devtools#234]
I follow the README and run "pnpm build", but it failed with Command "build" not found
It works if I "cd workspace/extension" first.

❯ pnpm --version
9.11.0

Shall we add "cd workspace/extension" to the README?

```diff
git clone https://github.com/sveltejs/svelte-devtools.git
cd svelte-devtools
pnpm install
+ cd workspace/extension
pnpm build
```

Also, "cd workspace/website" and running "pnpm build" throws error, too

error during build:
Error: src/app.html does not exist

**Comment by ignatiusmb** [comment]
Thanks! I've opened #235 to update the instructions. For `workspace/website`, it's expected to not work yet and will be fixed with #213, but there's some other plans going on that we'll need to wait merging that too.
