### ISSUE TITLE
[Bug] Base size too small on HiDPI screen

### ISSUE THREAD

**Issue by KaKi87** [sveltejs/svelte-devtools#57]
**Describe the bug**
Svelte Devtools base size for text and elements is too small on HiDPI screens.

**To Reproduce**
1. Install Svelte Devtools on a computer using a HiDPI screen

**Expected behavior**
Svelte Devtools would scale properly like Chrome Devtools does.

**Environment**
- Brave 1.25.73
- Svelte DevTools 1.3.0 from Chrome Web Store
- Svelte 3.32.3

**Additional context**

Chrome DevTools :

![2021-06-26 11_02_59-DesktopWindowXamlSource](https://user-images.githubusercontent.com/21284089/123508304-d3050400-d66e-11eb-86fa-c727ffbe6e8a.png)

Svelte DevTools :

![2021-06-26 11_03_29-DesktopWindowXamlSource](https://user-images.githubusercontent.com/21284089/123508303-d26c6d80-d66e-11eb-9348-33ec7f21fa2d.png)

---

Thanks

**Comment by robole** [comment]
This also applies to Firefox 93 (Ubuntu) also. Screen res: 1920 x 1080. Font size is smaller than regular devtools.

Svelte Devtool:

![Kazam_screenshot_00001](https://user-images.githubusercontent.com/3703647/136666280-23aaf88c-0820-4931-be71-9651c1b60673.png)

It does not increase in size when you zoom in with `Ctrl` + `+`.

Firefox Devtool:

![Kazam_screenshot_00002](https://user-images.githubusercontent.com/3703647/136666326-357d3427-d6e2-49fe-9c92-9856b7d07ecf.png)

**Comment by mgrubinger** [comment]
I agree, it's very hard to read.
Now that the extension kindof works again for Chrome(-ium) based browsers, it might be worth to start improving it? Not sure if builds would reach the Chrome/Firefox extension stores though. Does anyone have insights into the status of this project?
