### ISSUE TITLE
Does not work on extension pop-ups

### ISSUE THREAD

**Issue by avi12** [sveltejs/svelte-devtools#66]
**Describe the bug**
The last time I used Svelte Devtools on an [extension pop-up](https://developer.chrome.com/docs/extensions/reference/action) that uses Svelte (like [this one](/avi12/youtube-auto-hd)), Svelte Devtools didn't pick up on the web page being Svelte.

**To Reproduce**
1. After installing the devtools, open up the extension's devtools.
   This can be done by either:
   - Opening the pop-up, right-clicking → "Inspect element"
   - 1. Going to `chrome://extensions`
      2. Enabling "Developer mode"
      3. Right-clicking the extension → "Inspect pop-up window"
2. <img src="https://user-images.githubusercontent.com/6422804/140876330-cc960cf9-39a1-4539-a96e-a9bf241af11d.png" align="top" alt="Svelte not detected" />
3. Yes, "click here" doesn't help.

**Expected behavior**
The devtools should properly detect the Svelte instance,

**Environment**
 - Browser with version: Edge beta 96.0.1054.13
- Devtools version: 1.3.0
- Svelte version: [3.37.0](https://github.com/avi12/youtube-auto-hd/blob/main/package.json#L47)

**Comment by bershanskiy** [comment]
It's not really possible to do the way this extension works. There is simply no way for an extension to inject content scripts into another extension context.

One way to add this feature is to build target extension with a special module which would be injected into the target extension at that extension's build time. If this is important for you I could investigate this further.

**Comment by avi12** [comment]
I managed to make a couple of Svelte-based extensions without the Svelte devtools, but it'd be nice to have the devtools as an option to better debug the components

**Comment by jffaust** [comment]
+1 for this use case. I'm currently creating a browser extension with Svelte and being able to inspect the component hierarchy and state would be very useful.

**Comment by avi12** [comment]
> Although in my case it's not for the popup window of the extension but for a Svelte app injected as a content script.

Very interesting, I didn't know that Svelte can do that

**Comment by ignatiusmb** [comment]
I believe this should be possible with some work, but it's going to be really tricky as mentioned by @bershanskiy for starter. I'll revisit this to make sure it's possible in the first place and if the limitations and caveats are worth the effort.

**Comment by ignatiusmb** [comment]
It seems that the browser limits extensions to internal URLs such as `chrome://` or `chrome-extension://` by throwing either of the following errors, we can't really do anything about this.

```
Uncaught Error: Cannot access a chrome-extension:// URL of different extension
Uncaught Error: Cannot access chrome:// and edge:// URLs
```

**Comment by ignatiusmb** [comment]
Closing as unactionable per previous comment.

**Comment by avi12** [comment]
It's worth exploring setting up a local server just for the devtools
