### ISSUE TITLE
Introduce swiperjs in svelte and report errors in devtool debugging

### ISSUE THREAD

**Issue by mowtwo** [sveltejs/svelte-devtools#67]
**Describe the bug**
Hello, I introduced swiperjs in svelte and reported an error in devtool debugging

**To Reproduce**
1. Install swiperjs
2. Introduce and use swiperjs in your code
3. Open svelte-devtool and click "click here"
4. Console reports an error and devtool cannot work normally
![image](https://user-images.githubusercontent.com/41664636/147181711-99f06d11-801a-46b6-a7ca-d49bad804d8c.png)

**Expected behavior**
An error is reported and the root element displays an exception
![image](https://user-images.githubusercontent.com/41664636/147181237-2abeab68-6299-4962-8fea-b85f60b1437d.png)
![image](https://user-images.githubusercontent.com/41664636/147181832-c102c752-aebf-4c04-8c39-23250dff0664.png)
![image](https://user-images.githubusercontent.com/41664636/147181864-b7ddc125-3679-4671-93de-624b2b17de33.png)
![image](https://user-images.githubusercontent.com/41664636/147181419-e81845a9-6806-45db-a668-fcc4bac290c2.png)

**Environment**
- Microsoft Edge version 96.0.1054.62 
- Devtools version 1.3.0
- Svelte version 3.0.0
- Swiper version 7.3.4

**Comment by ignatiusmb** [comment]
Hi, can you provide a reproduction repository?

**Comment by ignatiusmb** [comment]
Closing as outdated, feel free to open another issue with a reproduction if the problem still persist
