### ISSUE TITLE
SvelteKit config

### ISSUE THREAD

**Issue by deshartman** [sveltejs/svelte-devtools#68]
Is there a way to enable DevTools for SvelteKit?

**Comment by vhscom** [comment]
For grins I added the following valid code to my SvelteKit config after adding the rollup plug-in (which is the kind of stuff that gets abstracted away by SvelteKit to begin with, thankfully):

```js
kit: {
  adapter: adapter(),
  files: { serviceWorker: 'src/sw' },
  serviceWorker: { register: true },
  vite: {
    build: {
      rollupOptions: {
        plugins: [
          svelte({
            compilerOptions: {
              dev: true
            }
          })
        ]
      }
    },
```

And nada.

I didn't dig any deeper as the inspector in DevTools proper is enough for my needs. Though I thought it would be nice to get a more focused slice of the data while I was building a model. I would expect svelte-devtools to work out of the box with SvelteKit without additional customization as SvelteKit already flags itself when it's running in development node.

@RedHatter I see this tools has not been very popular with the Sapper community based on the [trickle of related issues](https://github.com/RedHatter/svelte-devtools/search?q=sapper&type=issues) since 2019. What are your thoughts here?

**Comment by vhscom** [comment]
For grins I added the following to my SvelteKit config only half-expecting it to work:

```js
import svelte from 'rollup-plugin-svelte';

const config = {
  kit: {
    adapter: adapter(),
    vite: {
      build: {
        rollupOptions: {
          plugins: [ svelte({ compilerOptions: { dev: true } }) ]
        }
      },
      /* snip */
    }
  }
}
```

But nada.

I didn't dig any deeper as the inspector in DevTools proper is enough for my needs. Though I thought it would be nice to get a more focused slice of the data while I was building a model. If this does or were to work with SvelteKit, I would expect it to work out of the box with no peer dependencies required.

**Comment by vhscom** [comment]
For grins I added the following to my SvelteKit config only half-expecting it to work:

```js
import svelte from 'rollup-plugin-svelte';

const config = {
  kit: {
    adapter: adapter(),
    vite: {
      build: {
        rollupOptions: {
          plugins: [ svelte({ compilerOptions: { dev: true } }) ]
        }
      },
      /* snip */
    }
  }
}
```

But nada.

I didn't dig any deeper as the inspector in DevTools proper is enough for my needs. Though I thought it would be nice to get a more focused slice of the data while I was building a model. If this does or were to work with SvelteKit, I would expect it to work out of the box with no additional peer dependency installation required.

**Comment by Jakeii** [comment]
SvelteKit works out of the box for me, always has!

**Comment by Jakeii** [comment]
@vhscom works out of the box on firefox 99.0.1
<img width="1675" alt="Screenshot 2022-04-22 at 18 25 39" src="https://user-images.githubusercontent.com/1731150/164764269-d286badd-548d-441a-b802-979dae90b38c.png">

Just checked chrome and I see it doesn't work there

**Comment by vhscom** [comment]
> Just checked chrome and I see it doesn't work there

Thank you @Jakeii. I can confirm this works with LibreWolf Version 97.0-2 (64-bit) as well. Seems to be a Chromium-specific issue. I'm fairly confident it was working a few months ago on Chromium under Linux. Right now I'm on macOS. Will wait for others to chime in with more environment info to help isolate the issue. Cheers.

**Comment by vhscom** [comment]
FYI there's now a hot key activated inspector now built into vite-plugin-svelte. [Ref](https://twitter.com/SvelteSociety/status/1523340753719623680?s=19)

**Comment by vhscom** [comment]
[There's now](https://twitter.com/SvelteSociety/status/1523340753719623680) a hot key activated inspector built into `vite-plugin-svelte`. Unlike this tool it utilizes a popover which is novel but I'd still like to see all of my data together in one under dev tools.

**Comment by vhscom** [comment]
I learned from @dominikg `vite-plugin-svelte` (already included in kit) provides an experimental inspector now:

```js
experimental: {
  inspector: true
}
```

To use add the above to `svelte.config.js` at the same level as `kit` and save the file.
Press `Cmd+Shift` to activate or [customize options](https://github.com/sveltejs/vite-plugin-svelte/pull/322).

[Reference config](https://github.com/sveltejs/vite-plugin-svelte/blob/main/packages/playground/kit-demo-app/svelte.config.js#L16-L18) to example. [See StackBlitz](https://stackblitz.com/edit/sveltejs-kit-template-default-yuqc1k?file=svelte.config.js&terminal=dev) for demo.

**Comment by vhscom** [comment]
> [There's now](https://twitter.com/SvelteSociety/status/1523340753719623680) a hot key activated inspector built into `vite-plugin-svelte`.

I learned from @dominikg how to enable it.

```js
experimental: {
  inspector: true
}
```

Add the above to `svelte.config.js` at the same level as `kit` and save the file.
Press `Cmd+Shift` to activate or [customize options](https://github.com/sveltejs/vite-plugin-svelte/pull/322).

[Reference config](https://github.com/sveltejs/vite-plugin-svelte/blob/main/packages/playground/kit-demo-app/svelte.config.js#L16-L18) to example. [See StackBlitz](https://stackblitz.com/edit/sveltejs-kit-template-default-yuqc1k?file=svelte.config.js&terminal=dev) for demo.

**Comment by nrthbound** [comment]
> > [There's now](https://twitter.com/SvelteSociety/status/1523340753719623680) a hot key activated inspector built into `vite-plugin-svelte`.
> 
> I learned from @dominikg how to enable it.
> 
> ```js
> experimental: {
>   inspector: true
> }
> ```
> 
> Add the above to `svelte.config.js` at the same level as `kit` and save the file. Press `Cmd+Shift` to activate or [customize options](https://github.com/sveltejs/vite-plugin-svelte/pull/322).
> 
> [Reference config](https://github.com/sveltejs/vite-plugin-svelte/blob/main/packages/playground/kit-demo-app/svelte.config.js#L16-L18) to example. [See StackBlitz](https://stackblitz.com/edit/sveltejs-kit-template-default-yuqc1k?file=svelte.config.js&terminal=dev) for demo.

This doesn't really do anything useful as far as I can tell though. I can't monitor variables and see what the data is doing as I work through some testing scenarios. Am I missing something about this? After setting it up, it just lets me click the little Svelte logo and click on something on the page, which will take me to that line in VS Code. Not sure what I'm missing.

**Comment by mgrubinger** [comment]
@mshamaseen – Did you update to @sveltejs/kit@next and vite@latest? 
experimental now needs to be wrapped in `vitePlugin` which is a sibling of the `kit` key, like this:
```
const config = {
  kit: {
    // [....] kit options
  },
  vitePlugin: {
    experimental: {
      inspector: {
        showToggleButton: "always",
        toggleButtonPos: "bottom-right",
      },
    },
  },
};
```
see https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/config.md#experimental-options

**Comment by mshamaseen** [comment]
@mgrubinger here is my svelte.conf.js file:

```
import adapter from '@sveltejs/adapter-auto';
import preprocess from 'svelte-preprocess';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	// Consult https://github.com/sveltejs/svelte-preprocess
	// for more information about preprocessors
	preprocess: preprocess(),

	kit: {
		adapter: adapter()
	},
    vitePlugin: {
        experimental: {
            inspector: {
                showToggleButton: "always",
                toggleButtonPos: "bottom-right",
            },
        }
    }
};

export default config;
```

Now I can see the Svelte icon on the bottom-right, but I expected it to show information on the browser inspection. It keeps saying **To connect to Svelte perform a hard refresh (ctrl+F5) or click here.**

I tried to click on it and click on an item on the page, but nothing happened on the browser inspection side.

![image](https://user-images.githubusercontent.com/38951661/193628314-2f5bbcaa-7e7c-4888-ae08-3eb714b3ddf7.png)

**Comment by dominikg** [comment]
svelte inspector is a different tool, not related to svelte-devtools and not a browser extension.

**Comment by mshamaseen** [comment]
@dominikg Oh, I see.
I'm looking to activate the dev tool, I'm using Chrome (Version 106.0.5249.91 (Official Build) (64-bit)) on Linux 22.04 and the dev tool doesn't work.
I tried Firefox tho, it is working there.

Any info I can provide to help?
