### ISSUE TITLE
[Bug] Svelte Devtools not working using Svelte + Vite (Chromium based browsers)

### ISSUE THREAD

**Issue by Bellisario** [sveltejs/svelte-devtools#73]
**Describe the bug**
Svelte Devtools seems not to work using Svelte with Vite.

**To Reproduce**
Just start a new Vite project (with Svelte) and run in dev mode. You'll see Svelte Devtools doesn't recognise you're using Svelte in this page.

**Expected behavior**
Svelte Devtools should work with projects created with Vite, too.

**Environment**
 - Browser with version: Google Chrome, version 101.0.4951.67
- Devtools version: 1.3.0
- Svelte version: 3.44.0 (using _Vite 2.9.7_ and _vite-plugin-svelte 1.0.0-next.30_)

**Additional context**
None.

---

### Update - 07/11/2022

Seems this bug doesn't occur on Firefox but it's only Chromium based browsers related.

Re-tested myself using Chrome 107.0.5304.88: this is not working with Svelte 3.52.0 (using _Vite 3.1.8_ and _vite-plugin-svelte 1.1.0_).

**Comment by liuyiqi1999** [comment]
Same.

**Comment by beebase** [comment]
yep

**Comment by vhscom** [comment]
Related: https://github.com/RedHatter/svelte-devtools/issues/68

**Comment by Chuiantw1212** [comment]
Same.
Browser with version: Brave [Version 1.39.111 Chromium: 102.0.5005.61 (Official Build) (64-bit)]
Devtools version: 1.3.0
Svelte version: ^3.48.0 (using Vite 2.9.9 and vite-plugin-svelte 1.0.0-next.44)

**Comment by vhscom** [comment]
Note `vite-plugin-svelte` [has an inspector](https://github.com/RedHatter/svelte-devtools/issues/68#issuecomment-1139167798) now though I'd still like to get this one working again in Chrome 99+. There's a [pull open](https://github.com/RedHatter/svelte-devtools/pull/70) to address the bug and some users have already tried it and reported success.

**Comment by Bellisario** [comment]
Yes @vhscom I know there is an "internal" inspector but I'd like to try this one to have a better feeling like "normal" devtools.

**Comment by kwantopia** [comment]
Same here, it's not working with sample app from latest Sveltkit app.  

```
# pnpm-lock.yaml
svelte: 3.49.0
vite: 2.9.14
'@sveltejs/kit': 1.0.0-next.367_svelte@3.49.0+vite@2.9.14
```

```
# vite.config.js

import { sveltekit } from '@sveltejs/kit/vite';

/** @type {import('vite').UserConfig} */
const config = {
	plugins: [sveltekit({
		compilerOptions: {
			dev: true
		}
	})],
	mode:'development'
};

export default config;
```
@RedHatter any chance this could be resolved soon? Thanks!

**Comment by HNazmul** [comment]
yeah, some problem also for me.

**Comment by octoxan** [comment]
Saaame, is this extension abandoned?

**Comment by jercle** [comment]
Same here..

**Comment by kriddile** [comment]
Same

**Comment by bihongbin3027** [comment]
+1

**Comment by bihongbin3027** [comment]
+1

**Comment by xenogenesi** [comment]
Not working
svelte@3.49.0
both Firefox and Chromium == 106
svelte option enabled in vite.config compilerOptions: { dev: true }

**Comment by ghacosta** [comment]
**not working** on `"svelte": "^3.52.0",` with `Google Chrome Version 107.0.5304.87 (Official Build) (x86_64)`

**Comment by ghacosta** [comment]
tried adding mode: "development" 
```
import { defineConfig } from 'vite'
import { svelte } from '@sveltejs/vite-plugin-svelte'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [svelte()],
  mode:'development'
})
```

also tried with inspector enabled as specified here: https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/config.md#inspector

and finally tried running vite as `vite --debug` but didn't work either.

**Comment by XinChou16** [comment]
same, it's there are any solution?

**Comment by bershanskiy** [comment]
@XinChou16 Have you tried Chrome Beta 108?

**Comment by clouedoc** [comment]
so far, the best solution is to install Firefox for local development. That'll do in the meantime
- Camille



6 nov. 2022, 14:57 de ***@***.***:

**Comment by Bellisario** [comment]
@clouedoc yes, I just tried and seems to work with Firefox. This is very strange!
Anyway, I think this bug should be solved by developers, because there are lots of people (like me) using Chromium based browsers.

**Comment by mahdisalmanzade** [comment]
Still does not work in Chrome. :(

**Comment by BrianM0330** [comment]
This seems to be working for me on Brave browser (chromium based) version 108.
`[Version 1.46.144 Chromium: 108.0.5359.128 (Official Build) (arm64)](https://brave.com/latest/)`

The issue I was having was an adblocker that was enabled for localhost. Svelte devtools was unable to recognize the svelte instance in the window.

After disabling it and hard refreshing the browser, dev tools now picks up Svelte.

Try either disabling all ad blockers or opening the window in incognito with devtools active.

**Comment by Bellisario** [comment]
Working for me, too, on `Chrome 108.0.5359.124 (Official Build) (x86_64)`.

---

Please comment out some other positive feedback, so I can close the issue...

**Comment by queenkjuul** [comment]
When developing locally with vite 3.2.3 and Chrome 109.0.5414.87, the plugin does not work. Weirdly, when accessing my deployed Svelte site, the plugin recognizes it as Svelte and loads the tool. But without it recognizing the local vite server it's pretty useless

**Comment by ethanlal04** [comment]
Same. Its just a shame that one of the best web frameworks out there doesn't even have a proper debugging tool.

**Comment by ethanlal04** [comment]
Same. It's just a shame that one of the best web frameworks out there lacks even a proper debugging tool.

**Comment by MrBns** [comment]
what is the solution here ? ..

**Comment by sahilrajput03** [comment]
Not working for me either, svelte 5 setup.

**Comment by maietta** [comment]
Chiming in here to say it's not working for Firefox or Chrome for me on Linux. I suspect it's because I'm using Svelte 5.

**Comment by Dawit-Aseged** [comment]
Same new project. No dev tools

**Comment by Obehi** [comment]
Still not working in 2025

**Comment by lauta3011** [comment]
still not working :/

**Comment by joaowiciuk** [comment]
Not working for me as well

**Comment by juliarnasution** [comment]
still not working ....

**Comment by christiaan-janssen** [comment]
Chiming in, not working for me

**Comment by paschelino** [comment]
same here

**Comment by nicanordlc** [comment]
same

**Comment by rodolv-commons** [comment]
same

**Comment by MrBns** [comment]
I think this repo is abandoned.

**Comment by OlivierCoq** [comment]
This is still a problem in 2025
