### ISSUE TITLE
Is update planned?

### ISSUE THREAD

**Issue by bershanskiy** [sveltejs/svelte-devtools#90]
Hi, @benmccann are there any tentative plans regarding the next release?

For reference, Chromium 108 Canary fixed the bug breaking this extension, but it would be nice to have extension working before then. Also, I'll test on Chromium 108 Beta once it is released and update this issue.

**Comment by benmccann** [comment]
This repo was recently transferred to the Svelte org by the original creator, but we don't yet have publish rights in the webstore, so can't push any updates yet

**Comment by bbugh** [comment]
@Rich-Harris any chance we're going to give these folks publishing rights so they can update the extension?

**Comment by benmccann** [comment]
Rich doesn't have publishing rights either. Only the original author does. I'm trying to get that addressed

**Comment by bershanskiy** [comment]
I just checked on Google Chrome Beta 108 and Svelte Devtools worked fine.

Details:
 - Svelte Devtools 1.3.0 installed from CWS
 - Google Chrome Beta 108.0.5359.22
 - macOS Montrey 12.6 on MacBook Pro (Retina, 13-inch, Early 2015)

**Comment by bershanskiy** [comment]
For reference, Google Chrome 108 is planned to be released on November 29, just one month from now. I'm closing this as resolved then.
